### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tebriz159** [apiote/Bimba#4]
I just saw your project and I want to design a better logo for the project. I'll wait for your answer

**Comment by apiote** [comment]
That’s a great idea. What do You have in mind?

**Comment by tebriz159** [comment]
I want to make it with the letter B. Do you want a letter logo? Maybe thing like this 
![477-01](https://user-images.githubusercontent.com/31902754/38957740-3773072a-4310-11e8-882d-029323790793.png)

**Comment by tebriz159** [comment]
Hereəs my proposalş The background color is random color I can change it if you want

![x3](https://user-images.githubusercontent.com/31902754/39015357-080d1b0c-43d2-11e8-93d6-d4e242326482.png)

**Comment by apiote** [comment]
I don’t think I want a letter logo. It *is* beautiful and I *do* like it, but I think I’d like something connected with public transport or city life. Like the current logo was meant to be a [pantograph](https://en.wikipedia.org/wiki/Pantograph_(transport)).

When it comes to colours, I try to keep the style consistent with the new Poznań style [like under „Nowy wzór”](https://www.ztm.poznan.pl/assets/Uploads/_resampled/ResizedImageWzgzMiw1Mzhd/Legitymacja-kontrolerow-biletow-stary-i-nowy-wzor.png)—grey #3a3a3b (primary) and green #54af39 (accent)—or green and yellow like in the [major carrier company style](http://www.mpk.poznan.pl/)

**Comment by tebriz159** [comment]
I made this, maybe that's not what you want but I drew it as I understand.

![send](https://user-images.githubusercontent.com/31902754/39099114-8900c00c-4629-11e8-88ba-bca69bd8130d.png)

**Comment by apiote** [comment]
Wow! That looks perfect.

**Comment by apiote** [comment]
Great, thank You!

Do You want the images to be under certain (GNU GPL compatible) license or are You OK with them being a part of the whole GNU GPL licensed app?

**Comment by tebriz159** [comment]
I'm ok with the second option )

**Comment by apiote** [comment]
I’ve already applied the new logo in commit 28d5a58 (on branch v2.0-beta3) and when there’s enough changes I’ll merge it to master.
