### ISSUE TITLE
New Logo for Bimba

### ISSUE THREAD

**Issue by abdulmalikkhan655** [apiote/Bimba#9]
Hello   ,@apiote  I want contribute to Bimba so i designed a new logo for Bimba and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my designed

**Comment by apiote** [comment]
I appreciate but You’re a bit too late. I closed #4 and Bimba has a new logo as of 28d5a58 (on branch v2.0-beta3) and soon it’ll be on master.

**Comment by abdulmalikkhan655** [comment]
OK SIR
